config/routes.rb
FIN11Generator::Application.routes.draw do
  root :to => 'configuration_fields#index'
  resources :configuration_fields, only: [:index] do
    collection do
      post 'add_record'
      post 'clear_records'
      post 'delete_record'
      post 'generate_file'
      get 'acquirer_list'
      get 'currency_merchant_group_list'
    end
  end

end

app/models/acquirer.rb
class Acquirer < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :currency_merchant_groups, :dependent => :destroy
  attr_accessible :name, :code

  
  validates :name, :code, presence: true
end

app/models/base_currency.rb
class BaseCurrency < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :acquirers, :dependent => :destroy
  attr_accessible :currency

  validates :currency, presence: true
end

app/models/configuration_field.rb
class ConfigurationField < ActiveRecord::Base
	belongs_to :configuration_name
  	attr_accessible :name, :default_value, :state


  	scope :display, where(state: ["Mandatory", "Optional"])
  	scope :disabled_fields, where(state: "Disabled")
end

app/models/configuration_name.rb
class ConfigurationName < ActiveRecord::Base
	has_many :configuration_fields, :dependent => :destroy
	has_many :base_currencies, :dependent => :destroy
  	attr_accessible :name

  	validates :name, presence: true
end

app/models/currency_merchant_group.rb
class CurrencyMerchantGroup < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :name, :group_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :user_identifer
  helper_method :ip_identifer

  def ip_identifer
  	if request.env["HTTP_X_FORWARDED_FOR"]
  		 ip =  request.env["HTTP_X_FORWARDED_FOR"].split(",").first
  	elsif request.env["REMOTE_ADDR"]
  		 ip = request.env["REMOTE_ADDR"]
  	end
  	ip
  end

  def user_identifer
    logger.info "ITSTIGERTIME!!!!!!!!!!!!!!!"
    session[:user] ||= Time.now.to_i
    logger.info session[:user]
  end


end

app/controllers/configuration_fields_controller.rb
class ConfigurationFieldsController < ApplicationController
	before_filter :cached_records, only: [:add_record, :delete_record, :generate_file]

	MERCHANT_ID_CHARACTERS = 15

	def index
		cached_records
		@countries = Country.all
		gon.hiddenFields = ConfigurationField.disabled_fields.collect{|f| 	f.name.parameterize.gsub("company-s-","company-")}
	end

	def add_record
		logger.info "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
		logger.info session[:user]
		logger.info "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
		flash[:error] = nil
		# Gets the constant FIELD that contains the ordered parameters and parameterizes each value
		set_ordered_parameters

		fields = params[:fields]
		@mid = fields[:"merchant-id"]
		@tid = fields[:'terminal-id']
		if valid_mid_tid?(@mid + @tid) == false
			return
		end


		# Initialize record
		record = ""

		# looping ordered list
		# checking if parameters in form is present
		# Storing FIN11 record string

		@order.each do |o|
			if fields.include?(o)
				if o == "merchant-id"
					record += "0" * (MERCHANT_ID_CHARACTERS - fields[o].length) + fields[o] + ";"
				else
					record += (fields[o] + ";")
				end
			else
				record += ";"
			end
		end

		@records.nil? ? collated = [] : collated = @records
		# @record_sequence_no = (("0000000") + (collated.size + 1).to_s).last(7)
		# record += @record_sequence_no

		# rewrite collated value to records key after adding to FIN11 record string to collated array
		Rails.cache.write("records_#{session[:user]}", collated << record)
		logger.info Rails.cache.read("records_#{session[:user]}")
		cached_records
		@index = @records.rindex(record)
		@add_record = [collated.size.to_s, record]
	end

	def clear_records
		Rails.cache.write("records_#{session[:user]}", nil)
		Rails.cache.write("MID_TID_#{session[:user]}", nil)
		# redirect_to root_url
	end

	def delete_record
		flash[:error] = nil
		@deletion_index = params[:index].to_i
		mid_tid_records = Rails.cache.read("MID_TID_#{session[:user]}")
		# Rails.cache.write("records_#{ip_identifer}", @records.reject{|r| logger.info r; logger.info "record[#{@records.rindex(r)}== #{@deletion_index}] #{ @records.rindex(r) == @deletion_index}"; @records.index(r) == @deletion_index })
		@records.delete_at @deletion_index
		mid_tid_records.delete_at @deletion_index
		Rails.cache.write "records_#{session[:user]}", @records
		Rails.cache.write "MID_TID_#{session[:user]}", mid_tid_records
		#Set @records for re-rendering of records
		cached_records
	end

	def generate_file
		unless @records.nil?
			filename = "FIN11" + params[:file_date] + params[:file_time] + params[:file_base_currency_code] + params[:file_sequence_no] + params[:file_fcc_acquirer_id] + params[:file_version] + ".DAT"
			content = ""

			f = File.open("tmp/#{filename}", "w+")
			f.binmode
			
			content += "VOL1" + params[:file_date] + params[:file_time] + "\r\n"

			record_count = 0
			@records.each do |record|
				record_sequence_no = (("0000000") + (record_count += 1).to_s).last(7) + ";"
				content += record + record_sequence_no +"\r\n"
				record 
			end
			content += "UTL1" + ("0000000" + @records.size.to_s).last(7)
			f.write content
			f.close
			#### closing written file

			#### opening file to send data
			r = File.open("tmp/#{filename}", "r")
			send_data r.read, filename: filename
			r.close

			# Deletion of tmp filename
			File.delete("tmp/#{filename}")
		else
			flash[:error] = "no records"
			redirect_to root_url
		end
		# f = File.open("tmp/test.txt", "w+")
		# f.binmode
		# f.puts('test!')
		# f.puts "baana!"
		# f.close
		# send_file

		# File.delete("tmp/test.txt")

		# begin
		# 	f = File.open("tmp/test.txt", "w+")
		# 	f.binmode
		# 	f.write('test!')
		# 	f.close
		# ensure
		# 	send_file "tmp/test.txt", :x_sendfile => true
		# end
		# b = File.expand_path("tmp/test.txt")
		# FileUtils.remove_file(b)
	end

	def acquirer_list
		if !params[:currency].empty?
			@data = BaseCurrency.find_by_currency(params[:currency]).acquirers.collect {|acquirer| {:name => acquirer.name, :code => acquirer.code}}
		else
			@data = nil
		end

		respond_to do |format|
			format.js { render :json => @data}
		end
	end

	def currency_merchant_group_list
		if !params[:acquirer].empty?
			@data = Acquirer.find_by_code(params[:acquirer]).currency_merchant_groups.collect {|group| {:name => group.name, :group_id => group.group_id}}
		else
			@data = nil
		end

		respond_to do |format|
			format.js { render :json => @data}
		end
	end




	private

	def valid_mid_tid?(mid_tid)
		#Check if midtid already exists in array
		mid_tid_records = Rails.cache.read("MID_TID_#{session[:user]}")
		if mid_tid_records.nil?
			mid_tid_records = [mid_tid]
		else
			if mid_tid_records.include?(mid_tid)
				flash[:error] = "MID TID already exists. Change MID or TID"
				return false
			else
				mid_tid_records << mid_tid
			end
		end
		Rails.cache.write("MID_TID_#{session[:user]}", mid_tid_records, expires_in: 1.hour) if flash[:error].nil?
		return true
	end


	def cached_records
		@records = Rails.cache.read("records_#{session[:user]}") unless Rails.cache.read("records_#{session[:user]}").nil?
	end

	def set_ordered_parameters
		@order = []
		ORDERED_FIELD.each do |f|
			@order << f.parameterize.gsub("company-s-", "company-")
		end
		logger.info 'Order is '
		logger.info @order
		@order
	end

end

app/controllers/configuration_names_controller.rb
class ConfigurationNamesController < ApplicationController

	def new
		@config_name = ConfigurationName.new		
	end

	def create
		@config_name = ConfigurationName.new(params[:config_name].permit(:name))
		@config_name.save
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	ALERT_TYPES = [:error, :info, :success, :warning]

	def bootstrap_flash
		flash_messages = []
		flash.each do |type, message|
       # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
       next if message.blank?

       type = :success if type == :notice
       type = :error   if type == :alert
       next unless ALERT_TYPES.include?(type)

       Array(message).each do |msg|
       	text = content_tag(:div,
       		content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
       		msg.html_safe, :class => "alert fade in alert-#{type}")
       	flash_messages << text if message
       end
   end
   flash_messages.join("\n").html_safe
end
end

app/helpers/configuration_fields_helper.rb
module ConfigurationFieldsHelper
end

app/helpers/configuration_names_helper.rb
module ConfigurationNamesHelper
end

app/helpers/generator_helper.rb
module GeneratorHelper
end

app/views/configuration_fields/_fields.html.erb

<div class="form-container">
	<span class="span12">Add FIN11 records before generating a FIN11 file. TIDs for each record must be unique for each MID.</span>
	<%= form_tag nil, id: 'filename_form', remote: true do %>

	<div class="first-fields span12">

		<table class="form-fields span6" align="center">
			<tr>
				<td><%= label_tag :"base-currency-code", "Base Currency Code" %></td>
				<td><%= select_tag :"base-currency-code", options_for_select(["KRW", "USD"]), include_blank: "", class: "required" %></td>
			</tr>
			<tr>
				<td><%= label_tag :version, "Version" %></td>
				<td><%= text_field_tag :version, "0000", minlength: 4, maxlength: 4, class: "required digits", disabled: "disabled" %></td>
			</tr>
		</table>

	
		<table class="form-fields span6" align="center">
			<tr>
				<td><%= label_tag :"fcc-acquirer-id", "FCC Acquirer ID" %></td>
				<td><%= select_tag :"fcc-acquirer-id",  nil, class: "required" %></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
			</tr>
		</table>

	</div>
	<% end %>

	<%= form_tag add_record_configuration_fields_path, id: "generator_form", remote: true do %>
	<div>
		<div class="span5">
			<table class="form-fields record" align="center">
				<tr>
					<td>
						<!-- !!!!!!!this is renamed according to japan specifications!!!!!!! -->
						<%= label_tag :"merchant-category-code", "Currency Merchant Groups (FX Rate Margin)" %> 
					</td>
					<td>
						<%#= text_field_tag :"merchant-category-code", nil, maxlength: 3, number: true, name: "fields[merchant-category-code]", class: "required", placeholder: "%" %>
						<%= select_tag :"merchant-category-code", nil, name: "fields[merchant-category-code]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"point-of-sale-name", "Merchant Name" %>
					</td>
					<td>
						<%= text_field_tag :"point-of-sale-name", nil, maxlength: 64, name: "fields[point-of-sale-name]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"pos-contact-name", "Merchant Contact Name" %>
					</td>
					<td>
						<%= text_field_tag :"pos-contact-name", nil, maxlength: 50, name: "fields[pos-contact-name]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"point-of-sale-telephone", "Merchant Contact Number" %>
					</td>
					<td>
						<%= text_field_tag :"point-of-sale-telephone", nil, maxlength: 20, name: "fields[point-of-sale-telephone]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<!-- !!!!!!!this is renamed according to japan specifications!!!!!!! -->
						<%= label_tag :"company-fax-number", "Merchant Category" %>
					</td>
					<td>
						<%= text_field_tag :"company-fax-number", nil, minlength: 4,maxlength: 4, name: "fields[company-fax-number]", class: "required digits" %>
					</td>
				</tr>
<!-- 				<tr>
					<td>
						<%= label_tag :"creation-date", "Creation date" %>
					</td>
					<td>
						<%= text_field_tag :"creation-date", Date.today.to_s.gsub("-",""), minlength: 8, maxlength: 8, name: "fields[creation-date]", class: "required digits" %>
					</td>
					
				</tr>
				<tr>
					<td>
						<%= label_tag :"date-of-last-update", "Date of last update" %>
					</td>
					<td>
						<%= text_field_tag :"date-of-last-update", Date.today.to_s.gsub("-",""), minlength: 8, maxlength: 8, name: "fields[date-of-last-update]", class: "required digits" %>
					</td>
				</tr> -->
				<tr>
					<td>
						<%= label_tag :"terminal-status", "Terminal Status" %>
					</td>
					<td>
						<%= select_tag :"terminal-status", options_for_select([["Created", "C"], ["Installed", "I"], ["Deactivated", "D"]]), name: "fields[terminal-status]", class: "required" %>
					</td>
				</tr>
				
				<tr>
					<td>
						<%= label_tag :"company-legal-name", "Company's Legal Name" %>
					</td>
					<td>
						<%= text_field_tag :"company-legal-name", nil, maxlength: 64, name: "fields[company-legal-name]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"company-address", "Company's Address" %>
					</td>
					<td>
						<%= text_field_tag :"company-address", nil, maxlength: 50, name: "fields[company-address]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"contact-name", "Contact Name" %>
					</td>
					<td>
						<%= text_field_tag :"contact-name", nil, maxlength: 50, name: "fields[contact-name]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"company-telephone", "Company's telephone (include prefix)" %>
					</td>
					<td>
						<%= text_field_tag :"company-telephone", nil, maxlength: 20, name: "fields[company-telephone]", class: "digits" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"company-email", "Company's Email" %>
					</td>
					<td>
						<%= text_field_tag :"company-email", nil, maxlength: 50, name: "fields[company-email]", class: "email" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"terminal-manager", "FCC Sales/Account Manager" %>
					</td>
					<td>
						<%= text_field_tag :"terminal-manager", nil, maxlength: 64, name: "fields[terminal-manager]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"company-city", "Company's City" %>
					</td>
					<td>
						<%= text_field_tag :"company-city", nil, maxlength: 32, name: "fields[company-city]", class: "required" %>
					</td>
				</tr>
			</table>		
		</div>
		<div class="span2"></div>
		<div class="span5">
			<table class="form-fields record" align="center">
				<tr>
					<td>
						<%= label_tag :"merchant-id", "Merchant ID" %>
					</td>
					<td>
						<%= text_field_tag :"merchant-id", nil, maxlength: 15, name: "fields[merchant-id]", class: "digits required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"terminal-id", "Terminal ID" %>
					</td>
					<td>
						<%= text_field_tag :"terminal-id", nil, maxlength: 8, name: "fields[terminal-id]", class: "required digits" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"company-country", "Company's country" %>
					</td>
					<td>
						<%= select_tag :"company-country", options_for_select(@countries, selected: ["KR", "Korea, Republic of"]), name: "fields[company-country]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"point-of-sale-country", "Merchant Country (POS country)" %>
					</td>
					<td>
						<%= select_tag :"point-of-sale-country", options_for_select(@countries, selected: ["KR", "Korea, Republic of"]), name: "fields[point-of-sale-country]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"point-of-sale-address", "Merchant Address" %>
					</td>
					<td>
						<%= text_area_tag :"point-of-sale-address", nil, maxlength: 50, name: "fields[point-of-sale-address]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"point-of-sale-city", "Region (City)" %>
					</td>
					<td>
						<%= text_field_tag :"point-of-sale-city", nil, maxlength: 32,  name: "fields[point-of-sale-city]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"installation-date", "Terminal Installation Date" %>
					</td>
					<td>
						<%= text_field_tag :"installation-date", Date.today.to_s.gsub("-",""), minlength: 8, maxlength: 8, name: "fields[installation-date]", class: "required digits" %>
						<%= hidden_field_tag :"date-of-last-update", Date.today.to_s.gsub("-",""), name: "fields[date-of-last-update]" %>
						<%= hidden_field_tag :"creation-date", Date.today.to_s.gsub("-",""), name: "fields[creation-date]" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"model-of-pos", "Manufacturer/model of the POS" %>
					</td>
					<td>
						<%= text_field_tag :"model-of-pos", nil, maxlength: 50, name: "fields[model-of-pos]", class: "required" %>
					</td>
				</tr>
				
				<tr>
					<td>
						<%= label_tag :"point-of-sale-province", "Point of sale province" %>
					</td>
					<td>
						<%= text_field_tag :"point-of-sale-province", nil, maxlength: 10, name: "fields[point-of-sale-province]" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"point-of-sale-post-code", "Point of sale post code" %>
					</td>
					<td>
						<%= text_field_tag :"point-of-sale-post-code", nil, maxlength: 20, name: "fields[point-of-sale-post-code]" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"point-of-sale-fax-number", "Point of sale fax number (include prefix)" %>
					</td>
					<td>
						<%= text_field_tag :"point-of-sale-fax-number", nil, maxlength: 20, name: "fields[point-of-sale-fax-number]", class: "digits" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"point-of-sale-email", "Point of Sale email" %>
					</td>
					<td>
						<%= text_field_tag :"point-of-sale-email", nil, maxlength: 50, name: "fields[point-of-sale-email]", class: "email" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"company-province", "Company's province" %>
					</td>
					<td>
						<%= text_field_tag :"company-province", nil, maxlength: 10, name: "fields[company-province]" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"company-post-code", "Company's post code" %>
					</td>
					<td>
						<%= text_field_tag :"company-post-code", nil, maxlength: 20, name: "fields[company-post-code]" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"vat-number", "VAT Number" %>
					</td>
					<td>
						<%= text_field_tag :"vat-number", nil, maxlength: 20, name: "fields[vat-number]", class: "required digits" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"bank-id", "Bank ID" %>
					</td>
					<td>
						<%= text_field_tag :"bank-id", nil, maxlength: 5, name: "fields[bank-id]", class: "required" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"bank-agency-code", "Bank Agency Code(Sort Code)" %>
					</td>
					<td>
						<%= text_field_tag :"bank-agency-code", nil, maxlength: 10, name: "fields[bank-agency-code]" %>
					</td>
				</tr>
				<tr>
					<td>
						<%= label_tag :"bank-account", "Bank Account" %>
					</td>
					<td>
						<%= text_field_tag :"bank-account", nil, maxlength: 21, name: "fields[bank-account]" %>
					</td>
				</tr>
			</table>	
		</div>
	</div>

</div>

<% end %>


app/views/configuration_fields/_records.html.erb


<div align="center" id="tableContainer" class="table-container span12" >
	
	<div id="no-record-error"><%= bootstrap_flash %></div>
	<table cellpadding="10" cellspacing="0" width="900px" id="content-table">
		<thead class="fixedHeader">
			<tr class="alternateRow">
				<th width="5%">No.</th>
				<th width="80%">FIN11 Details</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% unless @records.nil? %>
				<% @records.each_with_index do |record, index| %>
				<tr class="record-rows" id="record-row-<%= index + 1 %>">
					<td width="5%"><%= "#{(index + 1)}." %></td>
					<td align="left"><%= record %></td>
					<td><%= link_to "Delete Record", delete_record_configuration_fields_path(index: index), method: "post", remote: true, class: "delete-record", id: "delete-record-#{index}", confirm: "Delete this record?" %></td>
				</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/configuration_fields/add_record.js.erb
$("#records-partial").html("<%= escape_javascript(render partial: 'records')%>" );
$("#added-record-no").text("<%= escape_javascript(@records.size.to_s) %>");
$("#record-mid").text("<%= escape_javascript(@mid) %>");
$("#record-tid").text("<%= escape_javascript(@tid) %>");

app/views/configuration_fields/clear_records.js.erb
$(".record-rows").remove();

app/views/configuration_fields/delete_record.js.erb
$("#records-partial").html("<%= escape_javascript(render partial: 'records') %>" )

app/views/configuration_fields/index.html.erb

<div class="span12">
	<h3 style="text-align:center;">FIN11 Generator</h3>
</div>
</br>

<%= render partial: "fields" %>
<div class="button-container">

	<ul class="nav nav-pills span12 add">
		<li class="nav-item"><%= button_tag "Add Record", {class: "btn btn-primary", id: "add-record"} %></li>
		<li class="nav-item"><%= button_tag("Reset Form", type: "button", class: "btn", id: "reset-button") %></li> 
		<li class="nav-item"><%= button_to('Clear All Listed Records', clear_records_configuration_fields_path, {:method => "post", remote: true, class: "btn btn-danger", confirm: "Are you sure?"}) %></li>
		<li class="nav-item">
			<%= form_tag generate_file_configuration_fields_path, id: "generate_file_form" do %>
			<%= hidden_field_tag "file_date" %>
			<%= hidden_field_tag "file_time" %>
			<%= hidden_field_tag "file_base_currency_code" %>
			<%= hidden_field_tag "file_fcc_acquirer_id" %>
			<%= hidden_field_tag "file_version" %>
			<%= submit_tag('Generate File', class: "btn btn-success", id: "generate_file") %>
		</li>
		<li class="nav-item">File Sequence No. <%= select_tag :file_sequence_no, options_for_select((1..10).map{|n| ["00#{n}", "00#{n}".last(3)]}) %></li>
		<% end %>
	</ul>

	<ul class="nav nav-pills span12">
		<li class="nav-item flash">Added Record: <span id="added-record-no">n/a</span>   MID: <span id="record-mid">n/a</span>   TID: <span id="record-tid">n/a</span></li>
	</ul>
	
</div>
<%#= button_to('TEST', clear_records_configuration_fields_path,
:method => "post", :remote => true) %>
<div id="records-partial">
<%= render partial: "records" %>
</div>



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= include_gon(:camel_case => true) %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "FIN11 Generator" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->

      <%= stylesheet_link_tag "application", :media => "all" %>

      <!-- For third-generation iPad with high-resolution Retina display: -->
      <!-- Size should be 144 x 144 pixels -->
      <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

      <!-- For iPhone with high-resolution Retina display: -->
      <!-- Size should be 114 x 114 pixels -->
      <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

      <!-- For first- and second-generation iPad: -->
      <!-- Size should be 72 x 72 pixels -->
      <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

      <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
      <!-- Size should be 57 x 57 pixels -->
      <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

      <!-- For all other devices -->
      <!-- Size should be 32 x 32 pixels -->
      <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    </head>
    <body>

      <div class="navbar navbar-fluid-top">
        <div class="navbar-inner">
          <div class="container-fluid">
   <!--        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a> -->
          <a class="brand" href="#"></a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%#= link_to "FIN11 Generator", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <!-- <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
            </ul>
          </div> -->
        </div>
        <div class="span8">
          
          <%= yield %>
        </div>
        <div class="span2">
        </div>
      </div><!--/row-->

      

    </div> <!-- /container -->
    <footer>
      <p><!-- &copy; Global Blue 2013 --></p>
    </footer>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
  </html>